destroy

diff --git a/.github/workflows/devsec.yml b/.github/workflows/devsec.yml
--- a/.github/workflows/devsec.yml
+++ b/.github/workflows/devsec.yml
@@ -88,16 +88,23 @@ jobs:
                   id: validate
                   run: terraform validate -no-color
           
-                - name: Terraform Plan
-                  id: plan
-                  if: github.event_name == 'pull_request'
-                  run: terraform plan -no-color -input=false
-                  continue-on-error: true
+                # - name: Terraform Plan
+                #   id: plan
+                #   if: github.event_name == 'pull_request'
+                #   run: terraform plan -no-color -input=false
+                #   continue-on-error: true
 
-                - name: Terraform Plan Status
-                  if: steps.plan.outcome == 'failure'
-                  run: exit 1
+                # - name: Terraform Plan Status
+                #   if: steps.plan.outcome == 'failure'
+                #   run: exit 1
           
+                # - name: Terraform Apply
+                #   if: github.ref == 'refs/heads/deploy' && github.event_name == 'push'
+                #   run: terraform apply -auto-approve -input=false
+
+                - name: Terraform Plan
+                  run: terraform plan
+        
                 - name: Terraform Apply
-                  if: github.ref == 'refs/heads/deploy' && github.event_name == 'push'
-                  run: terraform apply -auto-approve -input=false
+                  if: github.event_name == 'push' && contains(github.event.head_commit.message, 'deploy')
+                  run: terraform apply -auto-approve
